/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package menu.restoran;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.GraphicsEnvironment;
import java.awt.HeadlessException;
import java.awt.Point;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Deni Purwanto
 */
public class FormKategori extends javax.swing.JFrame {
    //objek yang diperlukan untuk mengelola database
    Statement stmt; //inteface untuk mengeksekusi query;
    Connection con;    //interface yang menyediakan method untuk menghubungi database;
    ResultSet rs;       // interface untuk menampung data hasil query.
    DefaultTableModel model;    //Menambahkan sebuah baris untuk ditempatkan di posisi terakhir dari model.
    String url = "jdbc:mysql://localhost:3306/menu_restorant";
    int id;

    /**
     * Creates new form FormKategori
     */
    public FormKategori() {
        initComponents();
        tabel();
        setIcon();
        initUI();
    }
    
    private void initUI(){ 
        getContentPane().setBackground(new Color(245, 245, 245));
        
        Dimension windowSize = getSize();
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        Point centerPoint = ge.getCenterPoint();
        int dx = centerPoint.x - windowSize.width / 2;
        int dy = centerPoint.y - windowSize.height / 2;    
        setLocation(dx, dy);
    }
    
     private void tabel()  {
    DefaultTableModel tb = new DefaultTableModel();
    // Memberi nama pada setiap kolom tabel
    tb.addColumn("Kategori");
    
    jTable2.setModel(tb);
    try {
           con = (Connection)konfig.configDB();     //memanggil koneksi yang terdapat pada class konfig
           Class.forName("com.mysql.cj.jdbc.Driver");
             stmt = con.createStatement();
        System.out.println("Database ditemukan");
        stmt = con.createStatement();    // Membuat objek statement
        // Mengambil data dari database
          rs= stmt.executeQuery("select *from kategori"); // eksekusi query dan menyimpan hasilnya di objek ResultSet
        
        while (rs.next())
        {
            // Mengambil data dari database berdasarkan nama kolom pada tabel
            // Lalu di tampilkan ke dalam JTable
            tb.addRow(new Object[] {
                //getString digunakan untuk mengambil kolom dengan tipe data string. 
                rs.getString (2),   
            });
        }
        String count_rows = String.valueOf(jTable2.getRowCount());
            lblcount_rows.setText("Jumlah Data : " + count_rows); //Menampilkan jumlah data yang ada pada tabel
    }catch ( SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        } catch (ClassNotFoundException cnfe){
            System.out.println("Pesan Error : " + cnfe); //Menampilkan Pesan error
        }
    }
    
    public void bersih(){
        txtkategori.setText(" ");
    }
    
    private void GetData_View(){
        int row = jTable2.getSelectedRow();
        String row_id = (jTable2.getModel().getValueAt(row, 0).toString());
        txtid.setText(row_id);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblcount_rows1 = new javax.swing.JLabel();
        btnedit = new javax.swing.JButton();
        txtid = new javax.swing.JLabel();
        btndelete = new javax.swing.JButton();
        btnadd = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        lbl_action = new javax.swing.JLabel();
        btnkembali = new javax.swing.JButton();
        lblcount_rows = new javax.swing.JLabel();
        panel = new javax.swing.JPanel();
        btnsave = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtkategori = new javax.swing.JTextField();
        btncancel = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblcount_rows2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(52, 58, 64));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 22)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Form Kategori");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("X");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("-");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 589, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(16, 16, 16))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 40));

        lblcount_rows1.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblcount_rows1.setForeground(new java.awt.Color(255, 255, 255));
        lblcount_rows1.setText("Terpilih :");
        lblcount_rows1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblcount_rows1MouseClicked(evt);
            }
        });
        getContentPane().add(lblcount_rows1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 470, 50, -1));

        btnedit.setBackground(new java.awt.Color(253, 126, 20));
        btnedit.setForeground(new java.awt.Color(255, 255, 255));
        btnedit.setText("Ubah");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });
        getContentPane().add(btnedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 70, -1));

        txtid.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 470, 60, 20));

        btndelete.setBackground(new java.awt.Color(220, 53, 69));
        btndelete.setForeground(new java.awt.Color(255, 255, 255));
        btndelete.setText("Hapus");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btndelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 80, -1));

        btnadd.setBackground(new java.awt.Color(0, 105, 217));
        btnadd.setForeground(new java.awt.Color(255, 255, 255));
        btnadd.setText("Tambah");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });
        getContentPane().add(btnadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTable2MouseReleased(evt);
            }
        });
        jTable2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable2KeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(jTable2);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 90, 460, 360));

        lbl_action.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lbl_action.setForeground(new java.awt.Color(255, 255, 255));
        lbl_action.setText("Tambah Data");
        getContentPane().add(lbl_action, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, -1, -1));

        btnkembali.setBackground(new java.awt.Color(253, 126, 20));
        btnkembali.setForeground(new java.awt.Color(255, 255, 255));
        btnkembali.setText("Kembali");
        btnkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkembaliActionPerformed(evt);
            }
        });
        getContentPane().add(btnkembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, 80, -1));

        lblcount_rows.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblcount_rows.setForeground(new java.awt.Color(255, 255, 255));
        lblcount_rows.setText("Jumlah Data ");
        lblcount_rows.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblcount_rowsMouseClicked(evt);
            }
        });
        getContentPane().add(lblcount_rows, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 180, -1));

        panel.setBackground(new java.awt.Color(52, 58, 64));
        panel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        panel.setForeground(new java.awt.Color(245, 245, 245));
        panel.setEnabled(false);

        btnsave.setBackground(new java.awt.Color(0, 105, 217));
        btnsave.setForeground(new java.awt.Color(255, 255, 255));
        btnsave.setText("Simpan");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Kategori");

        txtkategori.setBackground(new java.awt.Color(52, 58, 64));
        txtkategori.setForeground(new java.awt.Color(255, 255, 255));
        txtkategori.setBorder(null);
        txtkategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkategoriActionPerformed(evt);
            }
        });
        txtkategori.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtkategoriKeyTyped(evt);
            }
        });

        btncancel.setBackground(new java.awt.Color(220, 53, 69));
        btncancel.setForeground(new java.awt.Color(255, 255, 255));
        btncancel.setText("Batal");
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setBackground(new java.awt.Color(52, 58, 64));
        jLabel2.setForeground(new java.awt.Color(52, 58, 64));
        jLabel2.setText("null");

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(btncancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnsave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(txtkategori)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtkategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncancel)
                    .addComponent(btnsave)
                    .addComponent(jLabel2))
                .addGap(488, 488, 488))
        );

        getContentPane().add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, -1, 110));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/gambar.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 820, 480));

        lblcount_rows2.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        lblcount_rows2.setForeground(new java.awt.Color(255, 255, 255));
        lblcount_rows2.setText("Terpilih :");
        lblcount_rows2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblcount_rows2MouseClicked(evt);
            }
        });
        getContentPane().add(lblcount_rows2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 470, 50, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        // TODO add your handling code here:
        kategori  data = new kategori();
        // ambil input dari user
        data.setKategori(txtkategori.getText());
        String row_id = txtid.getText();
        if(!"0".equals(row_id)){
         try{
            int idktg = id;
            //query update
            String sql = "update kategori SET nama = '"+txtkategori.getText()+"' where id='"+idktg+"' ";  // query update
            con = (Connection)konfig.configDB();       //memanggil koneksi yang sudah dibuat pada class konfig untuk menjalankan query 
            Class.forName("com.mysql.cj.jdbc.Driver");
            stmt = con.prepareStatement(sql);
            stmt.executeUpdate(sql);    //update data
            JOptionPane.showMessageDialog(null, "Data berhasil di edit");  //notifikasi bahwa data berhasil di update
            tabel();    //memanggil fungsi tabel
            bersih();  //memanggil fungsi bersih
        }catch(HeadlessException | SQLException e){
            System.err.println("Error : " + e);  //untuk memeriksa suatu error pada program
        }  catch (ClassNotFoundException cnfe){
            System.out.println("Pesan Error : " + cnfe);
        }
        } else{
            JOptionPane.showMessageDialog(null, "Terdapat kesalahan id null!");
        }
    }//GEN-LAST:event_btneditActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        kategori  data = new kategori();
        // ambil input dari user
        data.setKategori(txtkategori.getText());
         int ok = JOptionPane.showConfirmDialog(null, "Apakah anda yakin ingin menghapus data ini?", "Pesan Peringatan", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        //Pertama, memeriksa apakah pengguna benar-benar ingin menghapus data, Jika mengklik "Ya", maka kode akan berlanjut.
        if (ok == 0) {  //kemudian menyetel pemeriksaan foreign key ke 0. Ini untuk mencegah kesalahan foreign key constraint.
            //query set_foreign_checks
            String sqly = "SET foreign_key_checks = 0";
            //query delete
            String sql = "DELETE FROM kategori WHERE nama='" + txtkategori.getText().trim() + "'";  // query delete
            try {
                stmt.execute(sqly);
                stmt.executeUpdate(sql);    //delete data
                sqly = "SET foreign_key_checks = 1";    //kemudian menyetel pemeriksaan foreign key ke 1.
                //Ini untuk mengaktifkan kembali pemeriksaan foreign key.
                stmt.execute(sqly);
                con = (Connection)konfig.configDB();    //memanggil koneksi yang sudah dibuat pada class konfig untuk menjalankan query 
                Class.forName("com.mysql.cj.jdbc.Driver");
                stmt = con.prepareStatement(sql);
                //kemudian menampilkan notifikasi untuk menginformasikan  bahwa data berhasil dihapus.
                JOptionPane.showMessageDialog(null, "Data Berhasil di Hapus", "Hapus Data", JOptionPane.INFORMATION_MESSAGE);
                txtkategori.setText("");    //mengosongkan form penginputan.
                tabel();    //memanggil fungsi tabel
                bersih();  //memanggil fungsi bersih
            } catch (HeadlessException |SQLException e) {
                System.err.println(sql);
                System.err.println("Error : " + e); //untuk memeriksa suatu error pada program
            } catch (ClassNotFoundException cnfe){
            System.out.println("Pesan Error : " + cnfe);
        }
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here:
        lbl_action.setText("Tambah Data");
        jTable2.clearSelection();
        btnsave.setText("Simpan");
        txtkategori.requestFocus();
    }//GEN-LAST:event_btnaddActionPerformed

    private void btnkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkembaliActionPerformed
        // TODO add your handling code here:
        Dashboard dashboard = new Dashboard();
        dashboard.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnkembaliActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
        kategori  data = new kategori();
        // ambil input dari user
        data.setKategori(txtkategori.getText());
        try{
            //query insert
            String sql = "insert into kategori (nama) values ('"+(txtkategori.getText())+"')";  // query simpan
            stmt.executeUpdate(sql);       //simpan data
            JOptionPane.showMessageDialog(null,"Data berhasil di simpan");  //notifikasi bahwa data berhasil disimpan
            tabel();    //memanggil fungsi tabel
            bersih();  //memanggil fungsi bersih
        } catch (SQLException ex){
            System.out.println("SQLException:"+ex.getMessage()); //untuk memeriksa suatu error pada program
        }
    }//GEN-LAST:event_btnsaveActionPerformed

    private void txtkategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkategoriActionPerformed

    private void txtkategoriKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtkategoriKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkategoriKeyTyped

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        // TODO add your handling code here:
        btnadd.doClick();
    }//GEN-LAST:event_btncancelActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        //jika data pada table diklik maka pada kolom texfield akan menampilkan data yang dipilih pada saat menekan data pada table
        //Membaca isi sel, lokasi baris dan kolom, Mengembalikan nilai indeks dari baris yang dipilih pertama
        txtkategori.setText(jTable2.getValueAt(jTable2.getSelectedRow(), 0).toString());
        try{
            int idktg;
            String namaktg = txtkategori.getText();
            rs = stmt.executeQuery("select * from kategori where nama='"+namaktg+"'"); //query untuk menampilkan data
            if(rs.next()){
                idktg = rs.getInt(1); //mendapatkan nilai kolom pertama di baris yang dipilih.
                id = idktg;
                //jLabel akan berubah nilai jika ada data baru yg disimpan di dalam tabel
                jLabel1.setText(Integer.toString(idktg)); // menetapkan teks ke nilai kolom kedua di baris yang dipilih.
                GetData_View();
            }
        } catch (SQLException ex){
            System.out.println("SQLException:"+ex.getMessage()); //untuk memeriksa suatu error pada program
        }
    }//GEN-LAST:event_jTable2MouseClicked

    private void lblcount_rowsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcount_rowsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblcount_rowsMouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        this.setState(FormKategori.ICONIFIED);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void lblcount_rows1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcount_rows1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblcount_rows1MouseClicked

    private void lblcount_rows2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcount_rows2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblcount_rows2MouseClicked

    private void jTable2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseReleased
        // TODO add your handling code here:
        GetData_View();
    }//GEN-LAST:event_jTable2MouseReleased

    private void jTable2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable2KeyReleased
        // TODO add your handling code here:
        GetData_View();
    }//GEN-LAST:event_jTable2KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormKategori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormKategori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormKategori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormKategori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormKategori().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnkembali;
    private javax.swing.JButton btnsave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lbl_action;
    private javax.swing.JLabel lblcount_rows;
    private javax.swing.JLabel lblcount_rows1;
    private javax.swing.JLabel lblcount_rows2;
    private javax.swing.JPanel panel;
    private javax.swing.JLabel txtid;
    private javax.swing.JTextField txtkategori;
    // End of variables declaration//GEN-END:variables

        private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Gambar/menu.png")));
    }
}
